version: 2.0.{build}-alpha
image: Visual Studio 2017
configuration: Debug
# branches:
#   only:
#     - master
#     - production
before_build:
  - nuget restore
build:
  project: Graphical.sln
  verbosity: minimal